package TeamCityNodePlugin.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '34708ac2-1d6f-4bcc-b3d0-9591ba63c50a' (id = 'TeamCityNodePlugin_TeamCityNodeVs91x')
accordingly, and delete the patch script.
*/
changeBuildType("34708ac2-1d6f-4bcc-b3d0-9591ba63c50a") {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
