package TeamCityNodePlugin.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '56017bf7-a20d-4e46-a917-a27c909d6b5a' (id = 'TeamCityNodePlugin_TeamCityNodeVs90x')
accordingly, and delete the patch script.
*/
changeBuildType("56017bf7-a20d-4e46-a917-a27c909d6b5a") {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
