package TeamCityNodePlugin.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '63558112-92ee-41d6-a7f7-827c633c5325' (id = 'TeamCityNodePlugin_TeamCityNodeVs100x')
accordingly, and delete the patch script.
*/
changeBuildType("63558112-92ee-41d6-a7f7-827c633c5325") {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
